# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Useful In Theory
email: mike.mull@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My blog wherein i discuss theoretical computer science from the
  perspective of a practicing programmer, and possibly other things
  upon which i have a tenuous grasp.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikemull.gitbuh.io" # the base hostname & protocol for your site
twitter_username: kwikstep
github_username:  mikemull

# Build settings
markdown: kramdown
